export const actionsTypes = {
  SET_USER: "SET_USER",
  SET_ORDERS: "SET_ORDERS",
  SELECTED_ORDERS: "SELECTED_ORDERS",
  DELETE_ORDERS: "DELETE_ORDERS",
  TOGGLE_MODAL_OPEN: "TOGGLE_MODAL_OPEN",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
};
