export const actionsTypes = {
  SET_USER: "SET_USER",
  SET_ORDERS: "SET_ORDERS",
  SELECTED: "SELECTED",
  DELETE_ORDERS: "DELETE_ORDERS",
  SHOW_PRODUCTS_FROM_ORDER: "SHOW_PRODUCTS_FROM_ORDER",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  SET_COORDINATES: "SET_COORDINATES",
  SET_WEATHER_DATA: "SET_WEATHER_DATA",
};
